import { Customer, MemberType, MaritalStatus, BackgroundTheme, BackgroundOption } from './types';

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 1,
    memberId: 'MBR001',
    name: 'Priya Sharma',
    memberType: MemberType.Silver,
    address: '2/101-Thirupathi Valley, Mumbai',
    mobile: '+91 9876543212',
    active: true,
    dob: '1990-03-23',
    maritalStatus: MaritalStatus.Married,
    city: 'Mumbai',
    pan: 'ABFPS1234A',
    aadhaar: '123412341234',
    anniversaryDate: '2015-04-20',
    policyRenewalDate: '2024-09-15',
    policyName: 'LIC Jeevan Umang',
    policyNumber: 'PID82934080',
  },
  {
    id: 2,
    memberId: 'MBR002',
    name: 'Deepa Singh',
    memberType: MemberType.Gold,
    address: '2/2334-Mullai Nagar, Delhi',
    mobile: '+91 3645386543',
    active: true,
    dob: '1985-07-15',
    maritalStatus: MaritalStatus.Single,
    city: 'Delhi',
    pan: 'CDEFP5678B',
    aadhaar: '567856785678',
    anniversaryDate: '',
    policyRenewalDate: '2025-01-10',
    policyName: 'HDFC Life Sanchay',
    policyNumber: 'HDFC987654',
  },
  {
    id: 3,
    memberId: 'MBR003',
    name: 'Kavya Reddy',
    memberType: MemberType.Diamond,
    address: '2/5443-TVS Motor, Bangalore',
    mobile: '+91 9675346573',
    active: true,
    dob: '1992-11-01',
    maritalStatus: MaritalStatus.Single,
    city: 'Bangalore',
    pan: 'EFGHI9012C',
    aadhaar: '901290129012',
    anniversaryDate: '',
    policyRenewalDate: '2024-11-20',
    policyName: 'ICICI Pru iProtect',
    policyNumber: 'ICICI12345',
  },
  {
    id: 4,
    memberId: 'MBR004',
    name: 'Ramya Patel',
    memberType: MemberType.Platinum,
    address: '3/445-Ram Nagar, Ahmedabad',
    mobile: '+91 8736283536',
    active: false,
    dob: '1980-01-30',
    maritalStatus: MaritalStatus.Widowed,
    city: 'Ahmedabad',
    pan: 'GHIJK3456D',
    aadhaar: '345634563456',
    anniversaryDate: '2005-06-12',
    policyRenewalDate: '2024-12-31',
    policyName: 'Max Life Smart Term',
    policyNumber: 'MAXL54321',
  },
];

export const BACKGROUND_OPTIONS: Record<BackgroundTheme, BackgroundOption> = {
  gradient: {
    name: 'Modern Gradient',
    class: 'bg-gradient-to-br from-blue-50 via-indigo-50 to-purple-50',
    description: 'Clean gradient with subtle colors',
    animated: false,
    isDark: false,
  },
  dark: {
    name: 'Dark Professional',
    class: 'bg-gradient-to-br from-gray-900 via-gray-800 to-black',
    description: 'Professional dark theme',
    animated: false,
    isDark: true,
  },
  ocean: {
    name: 'Ocean Calm',
    class: 'bg-gradient-to-br from-cyan-50 via-blue-100 to-indigo-200',
    description: 'Calming ocean-inspired theme',
    animated: false,
    isDark: false,
  },
  sunset: {
    name: 'Warm Sunset',
    class: 'bg-gradient-to-br from-orange-50 via-pink-50 to-red-100',
    description: 'Warm and welcoming atmosphere',
    animated: false,
    isDark: false,
  },
  nature: {
    name: 'Nature Fresh',
    class: 'bg-gradient-to-br from-green-50 via-emerald-50 to-teal-100',
    description: 'Fresh and natural feeling',
    animated: false,
    isDark: false,
  },
  minimal: {
    name: 'Pure Minimal',
    class: 'bg-white',
    description: 'Clean white background',
    animated: false,
    isDark: false,
  },
  particles: {
    name: 'Floating Particles',
    class: 'bg-gradient-to-br from-indigo-900 via-purple-900 to-pink-900',
    description: 'Animated floating particles',
    animated: true,
    isDark: true,
  },
  waves: {
    name: 'Ocean Waves',
    class: 'bg-blue-500',
    description: 'Animated wave patterns',
    animated: true,
    isDark: true,
  },
  aurora: {
    name: 'Aurora Borealis',
    class: 'bg-gradient-to-r from-purple-900 via-blue-900 to-indigo-900',
    description: 'Northern lights animation',
    animated: true,
    isDark: true,
  },
  cosmic: {
    name: 'Cosmic Stars',
    class: 'bg-gradient-to-br from-black via-blue-900 to-purple-900',
    description: 'Twinkling stars effect',
    animated: true,
    isDark: true,
  },
  prism: {
    name: 'Prism Light',
    class: 'bg-gradient-to-br from-pink-300 via-purple-300 to-indigo-400',
    description: 'Rainbow light refraction',
    animated: true,
    isDark: false,
  },
  matrix: {
    name: 'Digital Matrix',
    class: 'bg-gradient-to-br from-black via-green-900 to-black',
    description: 'Matrix-style digital rain',
    animated: true,
    isDark: true,
  },
  geometric: {
    name: 'Geometric Patterns',
    class: 'bg-gradient-to-br from-slate-100 via-gray-100 to-zinc-100',
    description: 'Animated geometric shapes',
    animated: true,
    isDark: false,
  },
  neon: {
    name: 'Neon Glow',
    class: 'bg-gradient-to-br from-black via-purple-900 to-pink-900',
    description: 'Glowing neon effects',
    animated: true,
    isDark: true,
  },
  forest: {
    name: 'Enchanted Forest',
    class: 'bg-gradient-to-br from-green-900 via-emerald-800 to-teal-900',
    description: 'Mystical forest atmosphere',
    animated: true,
    isDark: true,
  },
  galaxy: {
    name: 'Deep Galaxy',
    class: 'bg-gradient-to-br from-indigo-900 via-purple-900 to-pink-900',
    description: 'Swirling galaxy with nebula',
    animated: true,
    isDark: true,
  },
  crystal: {
    name: 'Crystal Cave',
    class: 'bg-gradient-to-br from-blue-100 via-cyan-50 to-teal-100',
    description: 'Crystalline light reflections',
    animated: true,
    isDark: false,
  },
  fire: {
    name: 'Flame Dance',
    class: 'bg-gradient-to-br from-red-900 via-orange-800 to-yellow-700',
    description: 'Dancing flame particles',
    animated: true,
    isDark: true,
  },
  electric: {
    name: 'Electric Storm',
    class: 'bg-gradient-to-br from-blue-900 via-indigo-900 to-purple-900',
    description: 'Lightning bolt effects',
    animated: true,
    isDark: true,
  },
  marble: {
    name: 'Marble Luxury',
    class: 'bg-gradient-to-br from-gray-50 via-slate-100 to-stone-200',
    description: 'Elegant marble texture',
    animated: false,
    isDark: false,
  },
  cyberpunk: {
    name: 'Cyberpunk City',
    class: 'bg-gradient-to-br from-black via-cyan-900 to-purple-900',
    description: 'Futuristic city vibes',
    animated: true,
    isDark: true,
  },
  rainbow: {
    name: 'Rainbow Spectrum',
    class: 'bg-gradient-to-br from-red-200 via-yellow-200 to-blue-200',
    description: 'Flowing rainbow colors',
    animated: true,
    isDark: false,
  },
  snow: {
    name: 'Winter Snow',
    class: 'bg-gradient-to-br from-blue-50 via-slate-50 to-gray-100',
    description: 'Gentle falling snow',
    animated: true,
    isDark: false,
  },
  sunsetGlow: {
    name: 'Sunset Glow',
    class: 'bg-gradient-to-r from-yellow-400 via-pink-500 to-red-500',
    description: 'Warm sunset glow with vibrant colors',
    animated: false,
    isDark: false,
  },
  midnightBlue: {
    name: 'Midnight Blue',
    class: 'bg-gradient-to-br from-blue-900 via-indigo-900 to-black',
    description: 'Deep midnight blue with subtle gradients',
    animated: false,
    isDark: true,
  },
  mintFresh: {
    name: 'Mint Fresh',
    class: 'bg-gradient-to-br from-green-200 via-green-300 to-green-400',
    description: 'Refreshing mint green shades',
    animated: false,
    isDark: false,
  },
  coralReef: {
    name: 'Coral Reef',
    class: 'bg-gradient-to-br from-pink-400 via-red-400 to-yellow-400',
    description: 'Bright coral reef inspired colors',
    animated: false,
    isDark: false,
  },
  twilightPurple: {
    name: 'Twilight Purple',
    class: 'bg-gradient-to-br from-purple-700 via-indigo-700 to-blue-700',
    description: 'Soft twilight purple hues',
    animated: false,
    isDark: true,
  },
  goldenHour: {
    name: 'Golden Hour',
    class: 'bg-gradient-to-br from-yellow-300 via-orange-300 to-red-300',
    description: 'Warm golden hour light',
    animated: false,
    isDark: false,
  },
  icyBlue: {
    name: 'Icy Blue',
    class: 'bg-gradient-to-br from-blue-100 via-blue-200 to-blue-300',
    description: 'Cool icy blue shades',
    animated: false,
    isDark: false,
  },
  forestMist: {
    name: 'Forest Mist',
    class: 'bg-gradient-to-br from-green-700 via-green-800 to-gray-900',
    description: 'Misty forest green tones',
    animated: false,
    isDark: true,
  },
  peachBlush: {
    name: 'Peach Blush',
    class: 'bg-gradient-to-br from-pink-200 via-pink-300 to-yellow-200',
    description: 'Soft peach blush colors',
    animated: false,
    isDark: false,
  },
  steelGray: {
    name: 'Steel Gray',
    class: 'bg-gradient-to-br from-gray-400 via-gray-500 to-gray-600',
    description: 'Cool steel gray gradient',
    animated: false,
    isDark: true,
  },
  beach: {
    name: 'Minimal Colors, Soft Beach',
    class: 'bg-gradient-to-br from-[#51e2f5] via-[#9df9ef] to-[#ffa8B6] dark:bg-[#a28089]',
    description: 'Blue, Pink, Green, Brown Web Design Color Scheme',
    animated: false,
    isDark: false,
  },
  purple90s: {
    name: 'Minimal Colors – Purple 90’s',
    class: 'bg-gradient-to-br from-[#a0d2eb] via-[#e5eaf5] to-[#d0bdf4] dark:bg-[#a28089]',
    description: 'Purple Blue, Slate White color Scheme',
    animated: false,
    isDark: false,
  },
  brightPower: {
    name: 'Bright Power',
    class: 'bg-gradient-to-br from-[#ff1d58] via-[#f75990] to-[#fff685] dark:bg-[#0049B7]',
    description: 'Gorgeous Web Design Color Scheme',
    animated: false,
    isDark: false,
  },
  rethink: {
    name: 'Rethink',
    class: 'bg-gradient-to-br from-[#ff1e00] via-[#e8f9fd] to-[#59ce8f]',
    description: 'Brightly Orange, Dimly Blue, Alert/Highlight Green',
    animated: false,
    isDark: false,
  },
  globalCharity: {
    name: 'Global Charity',
    class: 'bg-gradient-to-br from-[#f43a09] via-[#ffb766] to-[#c2edda] dark:bg-[#68d388]',
    description: 'Brightly Orange, Grandpa Orange, Grey Blue Green, Live Green',
    animated: false,
    isDark: false,
  },
  bankingFinance: {
    name: 'Banking and Finance',
    class: 'bg-gradient-to-br from-[#fbe3e8] via-[#5cbdb9] to-[#ebf6f5]',
    description: 'Pinky, Blue Greeny, Teeny Greeny',
    animated: false,
    isDark: false,
  },
  intenseGreenBlueRed: {
    name: 'Intense green, blue, and red',
    class: 'bg-gradient-to-br from-[#beef00] via-[#ff0028] to-[#657a00] dark:bg-[#1400c6]',
    description: 'Bright Green, Electric Red, Deep Green, Power Blue',
    animated: false,
    isDark: false,
  },
  whiteSpaceTanPurpleYellow: {
    name: 'White space, tan, purple, yellow',
    class: 'bg-gradient-to-br from-[#fceed1] via-[#7d3cff] to-[#f2d53c] dark:bg-[#c80e13]',
    description: 'Background Tan, Purple-y, Yellow Gloves, Redhead',
    animated: false,
    isDark: false,
  },
  deepBlueTan: {
    name: 'Deep blue and tan',
    class: 'bg-gradient-to-br from-[#e1b382] via-[#c89666] to-[#2d545e] dark:bg-[#12343b]',
    description: 'Sand Tan, Sand Tan Shadow, Night Blue, Night Blue Shadow',
    animated: false,
    isDark: false,
  },
  tanPinkRed: {
    name: 'Tan, pink and red',
    class: 'bg-gradient-to-br from-[#fff5d7] via-[#ff5e6c] to-[#feb300] dark:bg-[#ffaaab]',
    description: 'Ragin Beige, Coral Pink, Sleuthe Yellow, Pink Leaf',
    animated: false,
    isDark: false,
  },
  pinkGreenPurple: {
    name: 'Pink, Green, and Purple illustration',
    class: 'bg-gradient-to-br from-[#9bc400] via-[#8076a3] to-[#f9c5bd] dark:bg-[#7c677f]',
    description: 'Grassy Green, Purple Mountains Majesty, Misty Mountain Pink, Factory Stone Purple',
    animated: false,
    isDark: false,
  },
  brightColorful: {
    name: 'Bright and colorful',
    class: 'bg-gradient-to-br from-[#478559] via-[#161748] to-[#f95d9b] dark:bg-[#39a0ca]',
    description: 'Green Treeline, Purple baseline, Pink highlight, Bluewater lowlight',
    animated: false,
    isDark: false,
  },
  yellowRedPinkOrange: {
    name: 'Yellow, Red/Pink/Orange',
    class: 'bg-gradient-to-br from-[#ffde22] via-[#ff414e] to-[#ff8928] dark:bg-[#ffffff]',
    description: 'Yellow Background, Pink / Red Circle, Orange Circle, White Layover',
    animated: false,
    isDark: false,
  }
};
